name: get-started-with-postgres
root: <%= Dir.pwd %>

windows:
  - frontend:
      layout: main-vertical
      panes:
        - vim README.md
        - npm run db:start
        - sleep 2 && npm run db:connect
